# Police Station

In [ ]:
import pandas as pd
raw_police = pd.read_csv('raw/Police_Stations.csv')
raw_police.head().T

,0,1,2,3,4
X,141.798755,147.069628,143.940009,146.962049,145.055423
Y,-37.858419,-37.843433,-36.601704,-36.731794,-37.203405
objectid,1,2,3,4,5
featuretype,EMERGENCY FACILITY,EMERGENCY FACILITY,EMERGENCY FACILITY,EMERGENCY FACILITY,EMERGENCY FACILITY
descripton,An emergency management facility from which a ...,An emergency management facility from which a ...,An emergency management facility from which a ...,An emergency management facility from which a ...,An emergency management facility from which a ...
class,POLICING FACILITY,POLICING FACILITY,POLICING FACILITY,POLICING FACILITY,POLICING FACILITY
facility_name,BRANXHOLME POLICE STATION,BRIAGOLONG POLICE STATION,BRIDGEWATER POLICE STATION,BRIGHT POLICE STATION,BROADFORD POLICE STATION
facility_operationalstatus,OPERATIONAL,OPERATIONAL,OPERATIONAL,OPERATIONAL,OPERATIONAL
facility_address,NaN,NaN,NaN,NaN,NaN
abs_suburb,BRANXHOLME,BRIAGOLONG,BRIDGEWATER ON LODDON,BRIGHT,BROADFORD
facility_state,VICTORIA,VICTORIA,VICTORIA,VICTORIA,VICTORIA
abs_postcode,3302,3860,3516,3741,3658
facility_attribute_source,HTTP://DATA.VIC.GOV.AU,HTTP://DATA.VIC.GOV.AU,HTTP://DATA.VIC.GOV.AU,HTTP://DATA.VIC.GOV.AU,HTTP://DATA.VIC.GOV.AU
facility_attribute_date,NaN,NaN,NaN,NaN,NaN
facility_source,HTTP://DATA.VIC.GOV.AU,HTTP://DATA.VIC.GOV.AU,HTTP://DATA.VIC.GOV.AU,HTTP://DATA.VIC.GOV.AU,HTTP://DATA.VIC.GOV.AU
facility_date,NaN,NaN,NaN,NaN,NaN
facility_spatial_confidence,NaN,NaN,NaN,NaN,NaN
facility_revised,2018/05/15 00:00:00+00,2018/05/15 00:00:00+00,2018/05/15 00:00:00+00,2018/05/15 00:00:00+00,2018/05/15 00:00:00+00
comment_,NaN,NaN,NaN,NaN,NaN
facility_lat,-37.858419,-37.843433,-36.601704,-36.731794,-37.203405
facility_long,141.798755,147.069628,143.940009,146.962049,145.055423
validated,NaN,NaN,NaN,NaN,NaN
gnaf_building_name,NaN,NaN,NaN,NaN,NaN
gnaf_address_detail_pid,GAVIC424585730,GAVIC425609063,GAVIC720579618,GAVIC420915118,GAVIC421814544
gnaf_formatted_address,87-89 MONROE STREET,19-21 AVON STREET,38 PARK STREET,7 PARK STREET,156 HIGH STREET
gnaf_confidence,1.0,0.0,1.0,0.0,2.0
gnaf_postcode,3302.0,3860.0,3516.0,3741.0,3658.0
gnaf_suburb,BRANXHOLME,BRIAGOLONG,BRIDGEWATER ON LODDON,BRIGHT,BROADFORD
distance_to_gnaf,0.0,0.0,0.0,0.0,3.0
gnaf_lat,-37.858419,-37.843433,-36.601704,-36.731794,-37.203428
gnaf_long,141.798755,147.069628,143.940009,146.962049,145.05541

In [33]:
police_df = raw_police[raw_police['facility_state']=='VICTORIA']

police_df = police_df[['facility_name', 'abs_suburb', 'abs_postcode', 'facility_lat', 'facility_long', 'gnaf_formatted_address']]
police_df.rename(columns={'abs_suburb':'suburb',
                          'abs_postcode':'postcode',
                          'facility_lat':'lat',
                          'facility_long':'long',
                          'gnaf_formatted_address': 'formatted_address'
                          }, inplace=True)

police_df.head()

,facility_name,suburb,postcode,lat,long,formatted_address
0,BRANXHOLME POLICE STATION,BRANXHOLME,3302,-37.858419,141.798755,87-89 MONROE STREET
1,BRIAGOLONG POLICE STATION,BRIAGOLONG,3860,-37.843433,147.069628,19-21 AVON STREET
2,BRIDGEWATER POLICE STATION,BRIDGEWATER ON LODDON,3516,-36.601704,143.940009,38 PARK STREET
3,BRIGHT POLICE STATION,BRIGHT,3741,-36.731794,146.962049,7 PARK STREET
4,BROADFORD POLICE STATION,BROADFORD,3658,-37.203405,145.055423,156 HIGH STREET

In [45]:
police_df['suburb'] = police_df['suburb'].str.title()

police_df[police_df['postcode']==3000]

,facility_name,suburb,postcode,lat,long,formatted_address
178,MELBOURNE EAST POLICE STATION,Melbourne,3000,-37.816554,144.966375,228-232 FLINDERS LANE
179,AFP - VIC - MELBOURNE OFFICE,Melbourne,3000,-37.811623,144.958143,383 LA TROBE STREET

In [46]:
police_df.to_csv('police_station.csv', index=False)

# Lighting

In [ ]:
raw_light = pd.read_csv('raw/street-lights-with-emitted-lux-level-council-owned-lights-only.csv')
raw_light.head()

,geo_point_2d,geo_shape,prop_id,name,addresspt1,xorg,ext_id,asset_clas,label,asset_type,...,northing,str_id,addresspt,asset_subt,xsource,profile,xdate,xdrawing,mcc_id,roadseg_id
0,"-37.81373899955726, 144.9421289998664","{""coordinates"": [144.9421289998664, -37.81373899955726], ""type"": ""Point""}",0,NaN,0.0,ESG,210,NaN,6.549,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
1,"-37.81374400011677, 144.94213900036905","{""coordinates"": [144.94213900036905, -37.81374400011677], ""type"": ""Point""}",0,NaN,0.0,ESG,214,NaN,6.158,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
2,"-37.813802999768036, 144.94222000027733","{""coordinates"": [144.94222000027733, -37.813802999768036], ""type"": ""Point""}",0,NaN,0.0,ESG,251,NaN,54.448,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
3,"-37.81380999995285, 144.9422400005824","{""coordinates"": [144.9422400005824, -37.81380999995285], ""type"": ""Point""}",0,NaN,0.0,ESG,259,NaN,98.143,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
4,"-37.81351900001735, 144.94179300024945","{""coordinates"": [144.94179300024945, -37.81351900001735], ""type"": ""Point""}",0,NaN,0.0,ESG,77,NaN,18.280,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0

In [53]:
light_df = raw_light[[col for col in raw_light.columns if raw_light[col].nunique() > 1]].copy()
light_df['latitude'] = light_df['geo_point_2d'].str.split(', ').str[0].astype(float)
light_df['longitude'] = light_df['geo_point_2d'].str.split(', ').str[1].astype(float)

light_df.head()

,geo_point_2d,geo_shape,ext_id,label,latitude,longitude
0,"-37.81373899955726, 144.9421289998664","{""coordinates"": [144.9421289998664, -37.81373899955726], ""type"": ""Point""}",210,6.549,-37.813739,144.942129
1,"-37.81374400011677, 144.94213900036905","{""coordinates"": [144.94213900036905, -37.81374400011677], ""type"": ""Point""}",214,6.158,-37.813744,144.942139
2,"-37.813802999768036, 144.94222000027733","{""coordinates"": [144.94222000027733, -37.813802999768036], ""type"": ""Point""}",251,54.448,-37.813803,144.942220
3,"-37.81380999995285, 144.9422400005824","{""coordinates"": [144.9422400005824, -37.81380999995285], ""type"": ""Point""}",259,98.143,-37.813810,144.942240
4,"-37.81351900001735, 144.94179300024945","{""coordinates"": [144.94179300024945, -37.81351900001735], ""type"": ""Point""}",77,18.280,-37.813519,144.941793

In [54]:
# drop duplicates based on geo_shape, keeping only the record with latest ext_id
light_df = light_df.sort_values('ext_id', ascending=False)
light_df = light_df.drop_duplicates(subset=['geo_shape'])

In [50]:
light_df.nunique()

geo_point_2d    97405
geo_shape       97405
ext_id          97405
label            1016
latitude        97401
longitude       97398
dtype: int64

In [55]:
light_df = light_df[['latitude', 'longitude', 'ext_id', 'label']].rename(columns={'label': 'emitted_lux_level'})
light_df.nunique()

latitude             97401
longitude            97398
ext_id               97405
emitted_lux_level     1016
dtype: int64

In [58]:
light_df[['latitude', 'longitude']].value_counts()

latitude    longitude
-37.839828  144.981277    1
-37.805905  144.970771    1
-37.805901  144.971710    1
            144.971436    1
-37.805902  144.969543    1
                         ..
-37.817274  144.967358    1
-37.817275  144.967359    1
            144.967360    1
-37.817276  144.967361    1
-37.775433  144.938873    1
Name: count, Length: 97405, dtype: int64

In [72]:
light_location = light_df[['latitude', 'longitude']].drop_duplicates().copy()

light_location['lat_4'] = light_df['latitude'].round(4)
light_location['long_4'] = light_df['longitude'].round(4)

light_location_trim = light_location[['lat_4', 'long_4']].drop_duplicates().copy()
light_location_trim

         lat_4    long_4
68412 -37.8191  144.9472
12352 -37.8192  144.9472
14455 -37.8192  144.9473
68409 -37.8192  144.9474
98969 -37.8193  144.9474
...        ...       ...
39841 -37.8136  144.9420
62906 -37.8136  144.9419
1228  -37.8136  144.9418
68422 -37.8135  144.9418
51798 -37.8135  144.9417

[3930 rows x 2 columns]

In [ ]:
# from geopy.geocoders import Nominatim

# geolocator = Nominatim(user_agent="my_geopy_app")

# def get_postcode(row):
#     lat = row['lat_4']
#     lon = row['long_4']
#     full_address = geolocator.reverse((lat, lon)).raw['address']
#     suburb = full_address['suburb']
#     postcode = full_address['postcode']
#     return pd.Series([suburb, postcode])

# light_location_trim[['suburb', 'postcode']] = light_location_trim.apply(get_postcode, axis=1)

GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?lat=-37.8166&lon=144.9671&format=json&addressdetails=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

In [80]:
import time
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderUnavailable

geolocator = Nominatim(user_agent="my_geopy_app")

def get_postcode(lat, lon):
    retries = 3
    for attempt in range(retries):
        try:
            location = geolocator.reverse((lat, lon), exactly_one=True)
            address = location.raw.get('address', {})
            suburb = (
                address.get('suburb') or
                address.get('town') or
                address.get('village') or
                address.get('hamlet')
            )
            postcode = address.get('postcode')
            return pd.Series([suburb, postcode])
        except (GeocoderTimedOut, GeocoderUnavailable):
            time.sleep(2)
        except Exception:
            break
    return pd.Series([None, None])

results = []

for idx, row in light_location_trim.iterrows():
    lat, lon = row['lat_4'], row['long_4']
    result = get_postcode(lat, lon)
    results.append(result)
    time.sleep(1)  # Respect OpenStreetMap rate limit (max 1 request/sec)

light_location_trim[['suburb', 'postcode']] = results

light_location_trim.to_csv("geocoded_light_locations.csv", index=False)

In [83]:
light_location_trim.head()

         lat_4    long_4     suburb postcode
68412 -37.8191  144.9472  Docklands     3008
12352 -37.8192  144.9472  Docklands     3008
14455 -37.8192  144.9473  Docklands     3008
68409 -37.8192  144.9474  Docklands     3008
98969 -37.8193  144.9474  Docklands     3008

In [81]:
light_location_trim[['suburb', 'postcode']].value_counts()

suburb          postcode
Docklands       3008        1340
Parkville       3052         587
Melbourne       3000         495
East Melbourne  3002         486
Carlton         3053         380
Kensington      3031         194
Southbank       3006         143
Carlton North   3054         137
South Yarra     3141          60
East Melbourne  3000          45
South Yarra     3004          22
Princes Hill    3054          14
Parkville       3055           1
Name: count, dtype: int64

In [87]:
light_location

        latitude   longitude    lat_4    long_4
68412 -37.819103  144.947174 -37.8191  144.9472
56442 -37.819105  144.947177 -37.8191  144.9472
71876 -37.819108  144.947179 -37.8191  144.9472
75245 -37.819110  144.947182 -37.8191  144.9472
51779 -37.819112  144.947184 -37.8191  144.9472
...          ...         ...      ...       ...
61329 -37.813404  144.941696 -37.8134  144.9417
90046 -37.813403  144.941696 -37.8134  144.9417
12    -37.813402  144.941696 -37.8134  144.9417
55130 -37.813401  144.941696 -37.8134  144.9417
90044 -37.813400  144.941696 -37.8134  144.9417

[97405 rows x 4 columns]

In [97]:
light_location_encoded = pd.merge(light_location, light_location_trim, how='inner', on=['lat_4', 'long_4']) 
light_location_encoded.head()

    latitude   longitude    lat_4    long_4     suburb postcode
0 -37.819103  144.947174 -37.8191  144.9472  Docklands     3008
1 -37.819105  144.947177 -37.8191  144.9472  Docklands     3008
2 -37.819108  144.947179 -37.8191  144.9472  Docklands     3008
3 -37.819110  144.947182 -37.8191  144.9472  Docklands     3008
4 -37.819112  144.947184 -37.8191  144.9472  Docklands     3008

In [99]:
light_df = pd.merge(light_df, 
                    light_location_encoded[['latitude', 'longitude', 'suburb', 'postcode']], 
                    how='left', on=['latitude', 'longitude'])

In [100]:
light_df.to_csv('street_light.csv',index=False)

In [74]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="my_geopy_app")

lat = -37.839828
lon = 144.981277
address = geolocator.reverse((lat, lon)).raw['address']
print(f"{address['suburb']}, {address['postcode']}")

lat = round(lat, 4)
lon = round(lon, 4)
address = geolocator.reverse((lat, lon)).raw['address']
print(f"{address['suburb']}, {address['postcode']}")

South Yarra, 3141
South Yarra, 3141

In [77]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="my_geopy_app")


test = light_location.sample(n=15, random_state=42).copy()

def get_postcode(row):
    lat = row['latitude']
    lon = row['longitude']
    full_address = geolocator.reverse((lat, lon)).raw['address']
    suburb = full_address['suburb']
    postcode = full_address['postcode']
    return pd.Series([suburb, postcode])
test.apply(get_postcode, axis=1)

                     0     1
103424         Carlton  3053
20486        Melbourne  3000
31602        Parkville  3052
90956       Kensington  3031
29887   East Melbourne  3002
84550       Kensington  3031
103106  East Melbourne  3002
90611        Docklands  3008
8435     Carlton North  3054
63847      South Yarra  3141
88345        Docklands  3008
33524        Docklands  3008
20917        Parkville  3052
86676        Parkville  3052
66339        Parkville  3052

In [78]:

def get_postcode(row):
    lat = row['lat_4']
    lon = row['long_4']
    full_address = geolocator.reverse((lat, lon)).raw['address']
    suburb = full_address['suburb']
    postcode = full_address['postcode']
    return pd.Series([suburb, postcode])

test.apply(get_postcode, axis=1)

                     0     1
103424         Carlton  3053
20486        Melbourne  3000
31602        Parkville  3052
90956       Kensington  3031
29887   East Melbourne  3002
84550       Kensington  3031
103106  East Melbourne  3002
90611        Docklands  3008
8435     Carlton North  3054
63847      South Yarra  3141
88345        Docklands  3008
33524        Docklands  3008
20917        Parkville  3052
86676        Parkville  3052
66339        Parkville  3052

# Pedestrian Data (Historical 2024-2025)

In [ ]:
import pandas as pd
raw_ped = pd.read_csv('merged_pedestrian_counts.csv')
sensor_location = pd.read_csv('raw/pedestrian-counting-system-sensor-locations.csv')

In [ ]:
# Add geocoding on 
from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="my_geopy_app")

def get_postcode(location):    
    full_address = geolocator.reverse(location).raw['address']
    suburb = full_address['suburb']
    postcode = full_address['postcode']

    if postcode == '3000':
        suburb = 'Melbourne'
    return pd.Series([suburb, postcode])

sensor_location[['suburb', 'postcode']] = sensor_location['Location'].apply(get_postcode)

In [ ]:
sensor_location[['suburb', 'postcode']].value_counts()

In [ ]:
print(raw_ped['Sensing_Date'].min())
print(raw_ped['Sensing_Date'].max())

ped_df = raw_ped[(raw_ped['Sensing_Date']>='2024-04-01')&(raw_ped['Sensing_Date']<'2025-04-01')]
ped_df = ped_df[['Location_ID', 
                           'Sensing_Date', 
                           'HourDay',
                           'Total_of_Directions'
                           ]]

print(ped_df['Sensing_Date'].min())
print(ped_df['Sensing_Date'].max())

In [ ]:
# add period of time
def map_period(hour):
    if 0 <= hour <= 5:
        return '1. Late Night (12am-6am)'
    elif 6 <= hour <= 11:
        return '2. Morning (6am-12pm)'
    elif 12 <= hour <= 17:
        return '3. Afternoon (12pm-6pm)'
    else:
        return '4. Night (6pm-12am)'

ped_df['period_of_time'] = ped_df['HourDay'].apply(map_period)
ped_df.groupby('period_of_time').agg({'HourDay': ['min', 'max', pd.Series.nunique]})

In [ ]:
# aggregate to daily level 
ped_df = ped_df.groupby(['Location_ID', 'Sensing_Date', 'period_of_time'])['Total_of_Directions'].agg(
    total_pedestrian_count='sum',
    hours_covered='count' 
).reset_index()

In [ ]:
# aggregate to sensor level 
ped_df = ped_df.groupby(['Location_ID', 'period_of_time']).agg({
    'total_pedestrian_count': 'sum',
    'hours_covered': 'sum',
    'Sensing_Date': 'count'})\
    .rename(columns={'Sensing_Date': 'days_covered'})\
    .reset_index()

In [ ]:
# add sensor location
ped_df = pd.merge(ped_df,
                  sensor_location[['Location_ID', 
                                   'Sensor_Description', 
                                   'Sensor_Name', 
                                   'Latitude',
                                   'Longitude',
                                   'suburb', 
                                   'postcode'
                                   ]], 
                  on='Location_ID', how='left')
ped_df.columns = ped_df.columns.str.replace(r'[^\w]', '_', regex=True).str.lower()
ped_df.head()

In [ ]:
print(ped_df.shape)
ped_df.nunique()

In [ ]:
# Prepare export data
ped_df.to_csv('pedestrian.csv', index=False)